/*
squence 
주로 고유한 숫자값을 자동으로 생성해주는 객체로 자동 등기번호를 생성할때 사용합니다.
예를 들어, 회원가입할 때, 회원번호를 1,2,3순으로 자동 부여하고 싶을때 유용
squence는 자동으로 증가 하거나 감소 하는 숫자 시퀀스를 생성하는 데이터베이스 객체입니다.
주로 기본키(pk) 자동 생성 용도로 사용됩니다.
nextval,curval을 통해 다음 값 또는 현재값을 가져올 수 있습니다.
여러가지 조합으로 구성하는 식별데이터에서도 효율적으로 사용한다.
to_char(sysdate,'yy') ||'com',|| seq.nextval
start with: 처음 시작할 숫자 지정(기본값:1)
increment by: 증가 또는 감소 간격(기본값:1)
maxvalue: 시퀀스의 최대값 지정
minvalue: 시퀀스의 최소값 지정
cycle: 최대값 도달시 다시 처음으로 들어갈지 여부 
canhe: 메모리에 미리 시퀀스 값을 몇개 저장(기본값:20)
nocache: 매번 디스크에 값을 가져오도록 설정
order: 시퀀스 값이 생성된 순서를 보장
create sequence 시퀀스명; 1부터 시작하는
create sequence 시퀀스명
     start with 1000; 1000부터 시작하는 시퀀스 생성.
  시퀀스 활용
     시퀀스명.NEXTVAL : 1씩 카운트업..
     시퀀스명.CURRVAL : 현재 시퀀스번호
  시퀀스 삭제 
     DROP SEQUENCE 시퀀스명
          --------------------------------------------------
-- 1. 기존 잔여 시퀀스 정리
--------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE seq2';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
--------------------------------------------------
-- 1. 기존 객체 깔끔하게 삭제 (초기화)
--------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ01'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ02'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ03'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE EMP06_SEQ'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMP06 PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

--------------------------------------------------
-- 2. 기본 시퀀스 테스트 (SEQ01, SEQ02, SEQ03)
--------------------------------------------------
-- 기본 시퀀스 (1부터 시작, 1씩 증가)
CREATE SEQUENCE SEQ01;
SELECT SEQ01.NEXTVAL FROM DUAL; -- 결과: 1

-- 시작값이 1001인 시퀀스
CREATE SEQUENCE SEQ02
    START WITH 1001;
SELECT SEQ02.NEXTVAL FROM DUAL; -- 결과: 1001

-- 3씩 증가하는 시퀀스
CREATE SEQUENCE SEQ03
    INCREMENT BY 3;
SELECT SEQ03.NEXTVAL FROM DUAL; -- 결과: 1 (증가하며 호출)
SELECT SEQ03.CURRVAL FROM DUAL; -- 결과: 1 (현재 번호 호출)

--------------------------------------------------
-- 3. EMP06 테이블 생성 및 시퀀스 활용 데이터 삽입
--------------------------------------------------
-- EMP 테이블의 구조만 복사하여 EMP06 생성
CREATE TABLE EMP06
AS SELECT EMPNO, ENAME FROM EMP WHERE 1=0;

-- 1000부터 시작하는 EMP06전용 시퀀스 생성
CREATE SEQUENCE EMP06_SEQ
    START WITH 1000;

-- 시퀀스와 '익명' 이름으로 데이터 삽입
INSERT INTO EMP06 VALUES (EMP06_SEQ.NEXTVAL, '익명');
INSERT INTO EMP06 VALUES (EMP06_SEQ.NEXTVAL, '익명');
INSERT INTO EMP06 VALUES (EMP06_SEQ.NEXTVAL, '익명');

-- 변경사항 저장
COMMIT;

--------------------------------------------------
-- 4. 최종 결과 확인
--------------------------------------------------
SELECT * FROM EMP06;
dep02로 dept테이블을 구조로 복사하여 만들고 dept02_seq을 10부터 시작하여 1씩

증가하게 만들어 부서번호인 numbering하여 등록되게 처리
--------------------------------------------------
-- 1. 기존 객체 안전 삭제 (초기화 구문)
--------------------------------------------------
BEGIN 
    EXECUTE IMMEDIATE 'DROP SEQUENCE dept02_seq'; 
EXCEPTION 
    WHEN OTHERS THEN NULL; 
END;
/
--------------------------------------------------
-- 1. DDL: dept 테이블의 구조만 복사하여 dept02 생성
--------------------------------------------------
CREATE TABLE dept02
AS 
SELECT * 
FROM dept 
WHERE 1 = 0;

--------------------------------------------------
-- 2. SEQUENCE: 10부터 시작하여 1씩 증가하는 시퀀스 생성
--------------------------------------------------
CREATE SEQUENCE dept02_seq
    START WITH 10
    INCREMENT BY 1;

--------------------------------------------------
-- 3. DML: 시퀀스를 부서번호(DEPTNO)로 활용하여 데이터 등록
--------------------------------------------------
INSERT INTO dept02 (deptno, dname, loc) 
VALUES (dept02_seq.NEXTVAL, '익명', '서울');

INSERT INTO dept02 (deptno, dname, loc) 
VALUES (dept02_seq.NEXTVAL, '익명', '부산');

INSERT INTO dept02 (deptno, dname, loc) 
VALUES (dept02_seq.NEXTVAL, '익명', '대구');

-- 변경사항 영구 저장
COMMIT;

--------------------------------------------------
-- 4. DQL: 데이터 입력 결과 확인
--------------------------------------------------
SELECT * FROM dept02;
오라클 최신 버전 시퀀스 대체 기능: IDENTITY 컬럼
1. 오라클 12c 버전부터 도입된 IDENTITY 컬럼은 별도의 시퀀스(Sequence) 객체를 만들지 않고도
   테이블 안에서 알아서 차례대로 번호(1, 2, 3...)를 매겨주는 아주 편리하고 필수적인 기능입니다. 
   기존에는 시퀀스를 만들고 INSERT 할 때마다 NEXTVAL을 불러와야 했지만, 이제는 테이블을 만들 때
   옵션만 적어주면 데이터베이스가 알아서 순차적인 번호를 채워줍니다. 사람의 실수를 막아 데이터의 
   무결성을 지키면서도 쿼리 작성을 단순하게 만들어주어 널리 사용됩니다.

2. 핵심 키워드
   - GENERATED ALWAYS (항상 자동): 오직 시스템만 번호를 넣을 수 있습니다. 
        사람이 억지로 번호를 넣으려 하면 에러가 납니다. (무결성 완벽 보장)
   - GENERATED BY DEFAULT (기본 자동): 기본적으로는 알아서 번호를 주지만, 
        원한다면 사용자가 직접 특별한 번호를 콕 집어넣을 수 있습니다.
   - GENERATED BY DEFAULT ON NULL (빈칸도 자동): 사람이 번호를 직접 넣을 수도 있고, 
        실수나 편의상 빈칸(NULL)을 밀어 넣어도 에러 없이 알아서 자동 번호로 채워줍니다.
   - ISEQ$$... (내부 시퀀스): 개발자 눈에는 보이지 않지만, 데이터베이스 내부적으로 은닉되어 
       자동으로 만들어지는 시퀀스 이름입니다. 덕분에 고속 처리의 장점이 유지됩니다.
*/
/*
# 주요 IDENTITY 옵션 3총사 상세

1. 기본형 철통 보안 : GENERATED ALWAYS AS IDENTITY
   - 오직 데이터베이스가 자동으로 만들어주는 번호만 허용합니다. (가장 많이 쓰이고 안전합니다.)
   - 기본 구문: 컬럼명 NUMBER GENERATED ALWAYS AS IDENTITY
   - 활용: 게시글 번호나 회원 번호처럼 사용자가 마음대로 조작해서는 안 되는 중요한 기본키(Primary Key)에 주로 사용합니다.
          명시적으로 값을 INSERT 하려고 하면 ORA-32795 에러를 발생시킵니다.

2. 유연한 수동 입력 허용 : GENERATED BY DEFAULT AS IDENTITY
   - 평소에는 알아서 번호를 매겨주지만, 사용자가 직접 값을 입력하면 그 값이 들어갑니다.
   - 기본 구문: 컬럼명 NUMBER GENERATED BY DEFAULT AS IDENTITY
   - 활용: 평범한 순서대로 가다가 특정 상황(예: VIP 등장)에 점장이 수동으로 '777'번을 직접 지정해 주어야 하는 등, 
          상황에 따라 수동 입력이 필요할 때 사용합니다. (단, 대놓고 NULL을 강제로 넣으면 에러가 발생합니다.)

3. 빈칸도 찰떡같이 : GENERATED BY DEFAULT ON NULL AS IDENTITY
   - 수동 입력도 허용하면서, 사용자가 번호 칸에 아예 '빈칸(NULL)'을 넣고 보내더라도 시스템이 에러를 내지 않고 남는 
     번호로 알아서 채워줍니다.
   - 기본 구문: 컬럼명 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY
   - 활용: 화면(UI)이나 외부 시스템에서 번호를 비워둔 채(NULL)로 데이터를 넘겼을 때, 프로그램 수정 없이 DB 선에서 
     부드럽게 다음 자동 번호로 처리하고 싶을 때 유용합니다.
*/

/*
# IDENTITY 컬럼 적용 및 동작 원리
1. 테이블 생성만으로 시퀀스 생성과 트리거 연결 없이 자동 넘버링이 뚝딱 완성되는 유형을 말합니다.
2. 유형 및 관리 포인트
    1) 테이블 생성 시 속성 부여
        - 컬럼명 NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY
    2) 데이터 입력 방법
        - INSERT 문에서 번호 컬럼 자체를 빼고 작성하면 알아서 다음 번호가 들어갑니다.
        - 옵션(ALWAYS 등)에 따라 강제로 번호를 넣으려 하면 에러가 발생하여 실수를 막아줍니다.
    3) 데이터 딕셔너리 확인
        - USER_TAB_IDENTITY_COLS 뷰를 조회하여 현재 계정에 생성된 IDENTITY 컬럼 설정 및 상태를 
          언제든지 확인할 수 있습니다.
게시판 테이블에서 자동 번호 넘버링 옵션인 generated always as identity 옵션 설정 테이블 생성
CREATE TABLE NEW_BOARD(
    BOARD_NO NUMBER GENERATED always AS identity PRIMARY KEY,
    TITLE VARCHAR2(100)
);
SELECT * FROM NEW_BOARD;
-- 데이터 입력 (번호 컬럼 생략시 자동 넘버링)
INSERT INTO NEW_BOARD(TITLE) VALUES('최신 방식: 첫번째 글입니다!!');
INSERT INTO NEW_BOARD(TITLE) VALUES('최신 방식: 알아서 2번이 부여됩니다.');
SELECT * FROM NEW_BOARD
국장 닉 퓨리는 새로운 요원들을 등록 하려 합니다
대상 테이블은 shield agent
보안이 생명이므로 요원번호는 오직 시스템이 자동으로만 
부여 하며 누구도 임의로 번호를 조작 해서 넣을수 없어야 한다
(조건: agent_no는 숫자형 무조건 자동 발급 및 기본키, agent_name은 문자열, 요원 2명을 등록)
--------------------------------------------------
-- 1. 기존 테이블 정리 (초기화)
--------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE shield_agent PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------
-- 2. DDL: S.H.I.E.L.D. 요원 테이블 생성
-- GENERATED ALWAYS: 시스템 자동 발급 전용 (수동 입력/조작 불가)
--------------------------------------------------
CREATE TABLE shield_agent (
    agent_no   NUMBER GENERATED ALWAYS AS IDENTITY (START WITH 1001 INCREMENT BY 1),
    agent_name VARCHAR2(50) NOT NULL,
    CONSTRAINT pk_shield_agent PRIMARY KEY (agent_no)
);

--------------------------------------------------
-- 3. DML: 신규 요원 2명 등록 (agent_no는 시스템이 자동 부여)
--------------------------------------------------
INSERT INTO shield_agent (agent_name) VALUES ('콜슨');
INSERT INTO shield_agent (agent_name) VALUES ('메이');

-- 변경사항 영구 저장
COMMIT;

--------------------------------------------------
-- 4. DQL: 요원 등록 명단 확인
--------------------------------------------------
--------------------------------------------------
-- 1. 기존 테이블 삭제 (초기화)
--------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE wand_order PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------
-- 2. DDL: GENERATED BY DEFAULT ON NULL AS IDENTITY 적용
-- (직접 값 입력, NULL 입력 시 자동 번호 발급, 생략 시 자동 번호 발급 모두 허용)
--------------------------------------------------
CREATE TABLE wand_order (
    order_no    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    wizard_name VARCHAR2(50)
);

--------------------------------------------------
-- 3. DML: 3가지 유형 데이터 입력 테스트
--------------------------------------------------
-- Case 1: 직접 임의의 번호(6) 지정 삽입
INSERT INTO wand_order (order_no, wizard_name) VALUES (6, '해리포터');

-- Case 2: NULL을 명시적으로 전달 (ON NULL에 의해 자동으로 시퀀스 번호 발급)
INSERT INTO wand_order (order_no, wizard_name) VALUES (NULL, '론 위즐리');

-- Case 3: order_no 컬럼 자체를 생략 (DEFAULT 동작으로 자동 시퀀스 번호 발급)
INSERT INTO wand_order (wizard_name) VALUES ('헤르미온느');

-- 변경사항 저장
COMMIT;

--------------------------------------------------
-- 4. DQL: 결과 확인
--------------------------------------------------
SELECT * FROM wand_order;
======================================================================
마법 물약 창고 재고 관리 (GENERATED BY DEFAULT ON NULL) 
======================================================================
[상황]
마법 학교의 마법 물약 창고 관리 시스템입니다. 
학생들이 물약을 등록할 때 고유 번호(POTION_NO)를 직접 적어 내기도 하지만, 
외부 마법 기기에서 실수로 번호 값을 비워둔 채(NULL)로 전송하는 일도 잦습니다. 
시스템은 에러 없이 빈칸(NULL)을 감지하면 자동으로 다음 번호를 채워넣어야 합니다.

[미션]
POTION_NO: 숫자형, 수동 입력 허용 및 빈칸(NULL) 입력 시 자동 발급, 기본키
POTION_NAME: 문자열(50)
위 조건으로 'POTION_INVENTORY' 테이블을 생성하고, 번호 수동 입력, NULL 명시 입력, 컬럼 생략 입력을 각각 테스트해 보세요.
--------------------------------------------------
-- 1. 기존 테이블 정리 (초기화)
--------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE potion_inventory PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

--------------------------------------------------
-- 2. DDL: POTION_INVENTORY 테이블 생성
-- POTION_NO: 수동 입력 허용, NULL 또는 생략 시 자동 번호 발급 (PK)
--------------------------------------------------
CREATE TABLE potion_inventory (
    potion_no   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    potion_name VARCHAR2(50) NOT NULL
);

--------------------------------------------------
-- 3. DML: 3가지 입력 유형 테스트
--------------------------------------------------
-- [테스트 1] 번호 수동 입력 (100번으로 직접 지정)
INSERT INTO potion_inventory (potion_no, potion_name) 
VALUES (100, '폴리주스 물약');

-- [테스트 2] 외부 기기 오작동으로 NULL 명시 입력 (ON NULL에 의해 자동 발급)
INSERT INTO potion_inventory (potion_no, potion_name) 
VALUES (NULL, '행운의 약 (펠릭스 펠리시스)');

-- [테스트 3] 컬럼 자체를 생략하여 입력 (DEFAULT에 의해 자동 발급)
INSERT INTO potion_inventory (potion_name) 
VALUES ('사랑의 약 (아모텐시아)');

-- 변경사항 저장
COMMIT;

--------------------------------------------------
-- 4. DQL: 창고 재고 목록 확인
--------------------------------------------------
SELECT 
    potion_no   AS "물약 번호",
    potion_name AS "물약 이름"
FROM potion_inventory;
CREATE TABLE POTION_INVENTORY(
    POTION_NO NUMBER GENERATED BY default ON NULL AS identity PRIMARY KEY,
    POTION_NAME VARCHAR2(50)
);
-- 1. 고유번호를 직접 지정해 등록하는 경우
INSERT INTO POTION_INVENTORY(POTION_NO, POTION_NAME) VALUES(101,'풀리주스 마법약');
-- 2. 외부 시스템에서 실수로 번호에 NULL을 밀어 넣는 경우(에러 없이 자동 번호 발급)
INSERT INTO POTION_INVENTORY(POTION_NO, POTION_NAME) VALUES(NULL,'펠릭스 펠리시스(행운의 물약)');
-- 3. 번호 컬럼 자체를 생략하고 등록하는 경우(당연히 자동 발급)
INSERT INTO POTION_INVENTORY(POTION_NAME) VALUES('사랑의 묘약');
SELECT * FROM POTION_INVENTORY;

*/
